version: '3'

services:
  nginx:
    container_name: app-front
    image: nginx
    restart: always
    ports:
      - '8080:80'
      #- '9000:9000'
    volumes:
      - '${PHP_APP_FOLDER}:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - '/tmp/${APP_NAME}/nginx:/var/log/nginx'
    env_file:
      - '.env'
    networks:
      - app-network
    depends_on:
      - 'php-fpm'


  php-fpm:
    container_name: php-fpm
    restart: always
    build:
      context: ./
      dockerfile: './docker/php-fpm/build/Dockerfile'
      args: 
      - INSTALL_COMPOSER=${PHP_INSTALL_COMPOSER}
      - INSTALL_NODE=${PHP_INSTALL_NODE}
      - INSTALL_XDEBUG=${PHP_INSTALL_XDEBUG}
      - INSTALL_ORACLE=${PHP_INSTALL_ORACLE}
      - INSTALL_POSTGRES=${PHP_INSTALL_POSTGRES}
      - INSTALL_MYSQL=${PHP_INSTALL_MYSQL}
      - APP_FOLDER=${PHP_APP_FOLDER}
    #ports:
      #- '9000:9000'
    volumes:
      - '${PHP_APP_FOLDER}:/var/www/html'
      - './docker/xdebug/php-dev.ini:/usr/local/etc/php/conf.d/php-dev.ini'
      - '/tmp/${APP_NAME}/php-fpm:/var/log/xdebug'
    environment:
      - XDEBUG_CONFIG="remote_host=${HOST_IP}"
      - PHP_IDE_CONFIG="serverName=${HOST_SERVER_NAME}"
    env_file:
      - '.env'
    networks:
      - app-network

  postgresql:
    container_name: postgresql
    restart: always
    build:
      context: .
      dockerfile: ./docker/postgres/build/Dockerfile
    environment:
      - POSTGRES_DB=${PGQSL_DB_NAME}
      - POSTGRES_USER=${PGQSL_USER}
      - POSTGRES_PASSWORD=${PGQSL_PASSWORD}
    volumes:
     # - "${PGQSL_INIT}:/docker-entrypoint-initdb.d/"
      - "pgdata:/var/lib/postgresql/data/"
    env_file:
      - '.env'
    networks:
      - app-network
  #MySQL Service
  mysql:
    image: mysql:8.0
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    container_name: mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
    volumes:
      - 'mysqldata:/var/lib/mysql'
      - '${MYSQL_INIT}:/docker-entrypoint-initdb.d'
    env_file:
      - '.env'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  mysqldata:
  pgdata:
